DanglingStorageURLError: introduce msg attribute.
--HG--
extra : rebase_source : f4586138deb0e31e6e3b9121b0e9aa91a68eee55
extra : histedit_source : 45ed2aff150acfc286c1d80bd0f296dcb67134e2